// Complete dataset generated on 2025-09-29 18:26:13.457030
// Total symbols: 35
const varData = {
            "EURGBP": {
                        "var": 456.87123,
                        "price": 0.87278,
                        "sector": "Currency",
                        "description": "Euro vs Great Britain Pound ",
                        "asset_class": "futures",
                        "atr_d1": 0.003039,
                        "atr_w1": 0.008118,
                        "atr_mn1": 0.018601,
                        "outliers": [],
                        "ev_data": {}
            },
            "EURUSD": {
                        "var": 859.269759,
                        "price": 1.17247,
                        "sector": "Currency",
                        "description": "Euro vs US Dollar",
                        "asset_class": "futures",
                        "atr_d1": 0.007713,
                        "atr_w1": 0.018152,
                        "atr_mn1": 0.041244,
                        "outliers": [],
                        "ev_data": {}
            },
            "GBPUSD": {
                        "var": 1019.913819,
                        "price": 1.34336,
                        "sector": "Currency",
                        "description": "Great Britan Pound vs US Dollar",
                        "asset_class": "futures",
                        "atr_d1": 0.008689,
                        "atr_w1": 0.021054,
                        "atr_mn1": 0.049542,
                        "outliers": [],
                        "ev_data": {}
            },
            "6A_Z": {
                        "var": 450.573075,
                        "price": 0.65825,
                        "sector": "Currency",
                        "description": "Australian Dollar December",
                        "asset_class": "futures",
                        "atr_d1": 0.004568,
                        "atr_w1": 0.011611,
                        "atr_mn1": 0.029532,
                        "outliers": [],
                        "ev_data": {}
            },
            "6B_Z": {
                        "var": 635.753644,
                        "price": 1.3435,
                        "sector": "Currency",
                        "description": "British Pound December",
                        "asset_class": "futures",
                        "atr_d1": 0.008471,
                        "atr_w1": 0.020936,
                        "atr_mn1": 0.04945,
                        "outliers": [],
                        "ev_data": {}
            },
            "6C_Z": {
                        "var": 273.119554,
                        "price": 0.7209,
                        "sector": "Currency",
                        "description": "Canadian Dollar December",
                        "asset_class": "futures",
                        "atr_d1": 0.002811,
                        "atr_w1": 0.007232,
                        "atr_mn1": 0.019743,
                        "outliers": [],
                        "ev_data": {}
            },
            "6E_Z": {
                        "var": 1078.739614,
                        "price": 1.1777,
                        "sector": "Currency",
                        "description": "Euro FX December",
                        "asset_class": "futures",
                        "atr_d1": 0.007711,
                        "atr_w1": 0.0182,
                        "atr_mn1": 0.041421,
                        "outliers": [],
                        "ev_data": {}
            },
            "6J_Z": {
                        "var": 596.736324,
                        "price": 0.006777,
                        "sector": "Currency",
                        "description": "Japanese Yen December",
                        "asset_class": "futures",
                        "atr_d1": 4.8e-05,
                        "atr_w1": 0.000122,
                        "atr_mn1": 0.000346,
                        "outliers": [],
                        "ev_data": {}
            },
            "6N_Z": {
                        "var": 538.259255,
                        "price": 0.57955,
                        "sector": "Currency",
                        "description": "New Zeland Dollar December",
                        "asset_class": "futures",
                        "atr_d1": 0.004561,
                        "atr_w1": 0.011725,
                        "atr_mn1": 0.029221,
                        "outliers": [],
                        "ev_data": {}
            },
            "6S_Z": {
                        "var": 1302.015235,
                        "price": 1.26495,
                        "sector": "Currency",
                        "description": "Swixx Franc December",
                        "asset_class": "futures",
                        "atr_d1": 0.008225,
                        "atr_w1": 0.018957,
                        "atr_mn1": 0.038893,
                        "outliers": [],
                        "ev_data": {}
            },
            "BZ_Z": {
                        "var": 1459.177999,
                        "price": 66.82,
                        "sector": "Commodities",
                        "description": "Brent Crude Oil December",
                        "asset_class": "futures",
                        "atr_d1": 1.432857,
                        "atr_w1": 3.461429,
                        "atr_mn1": 7.472143,
                        "outliers": [],
                        "ev_data": {}
            },
            "CL_X": {
                        "var": 1521.130099,
                        "price": 63.23,
                        "sector": "Commodities",
                        "description": "Light Sweet Crude November",
                        "asset_class": "futures",
                        "atr_d1": 1.482857,
                        "atr_w1": 3.940714,
                        "atr_mn1": 7.797143,
                        "outliers": [],
                        "ev_data": {}
            },
            "ES_Z": {
                        "var": 2341.787724,
                        "price": 6713.25,
                        "sector": "Indexes",
                        "description": "E-Mini S&P 500 December",
                        "asset_class": "futures",
                        "atr_d1": 52.660714,
                        "atr_w1": 144.25,
                        "atr_mn1": 400.892857,
                        "outliers": [],
                        "ev_data": {}
            },
            "GC_Z": {
                        "var": 4670.316764,
                        "price": 3856.7,
                        "sector": "Commodities",
                        "description": "Gold December",
                        "asset_class": "futures",
                        "atr_d1": 48.735714,
                        "atr_w1": 108.278571,
                        "atr_mn1": 235.635714,
                        "outliers": [],
                        "ev_data": {}
            },
            "HE_V": {
                        "var": 632.197878,
                        "price": 101.1,
                        "sector": "Utilities",
                        "description": "Lean Hogs October",
                        "asset_class": "futures",
                        "atr_d1": 1.326786,
                        "atr_w1": 3.225,
                        "atr_mn1": 5.864286,
                        "outliers": [],
                        "ev_data": {}
            },
            "HG_Z": {
                        "var": 2551.769019,
                        "price": 4.9105,
                        "sector": "Commodities",
                        "description": "Copper December",
                        "asset_class": "futures",
                        "atr_d1": 0.087107,
                        "atr_w1": 0.342036,
                        "atr_mn1": 0.641786,
                        "outliers": [],
                        "ev_data": {}
            },
            "HO_X": {
                        "var": 2513.625714,
                        "price": 2.3365,
                        "sector": "Commodities",
                        "description": "Heating Oil November",
                        "asset_class": "futures",
                        "atr_d1": 0.055764,
                        "atr_w1": 0.136307,
                        "atr_mn1": 0.243479,
                        "outliers": [],
                        "ev_data": {}
            },
            "KE_Z": {
                        "var": 491.145127,
                        "price": 507.25,
                        "sector": "Commodities",
                        "description": "Hard Red Wheat December",
                        "asset_class": "futures",
                        "atr_d1": 9.285714,
                        "atr_w1": 21.535714,
                        "atr_mn1": 61.0,
                        "outliers": [],
                        "ev_data": {}
            },
            "LE_V": {
                        "var": 1534.57411,
                        "price": 231.3,
                        "sector": "Commodities",
                        "description": "Live Cattle October",
                        "asset_class": "futures",
                        "atr_d1": 3.598214,
                        "atr_w1": 7.344643,
                        "atr_mn1": 12.869643,
                        "outliers": [],
                        "ev_data": {}
            },
            "LE_Z": {
                        "var": 1673.06601,
                        "price": 233.8,
                        "sector": "Commodities",
                        "description": "Live Cattle December",
                        "asset_class": "futures",
                        "atr_d1": 3.919643,
                        "atr_w1": 7.35,
                        "atr_mn1": 11.375,
                        "outliers": [],
                        "ev_data": {}
            },
            "NG_X": {
                        "var": 1055.26997,
                        "price": 3.266,
                        "sector": "Commodities",
                        "description": "Natural Gas November",
                        "asset_class": "futures",
                        "atr_d1": 0.114714,
                        "atr_w1": 0.342286,
                        "atr_mn1": 1.081214,
                        "outliers": [],
                        "ev_data": {}
            },
            "NQ_Z": {
                        "var": 3963.798623,
                        "price": 24834.25,
                        "sector": "Indexes",
                        "description": "E-mini Nasdaq 100 December",
                        "asset_class": "futures",
                        "atr_d1": 249.303571,
                        "atr_w1": 674.982143,
                        "atr_mn1": 1920.089286,
                        "outliers": [],
                        "ev_data": {}
            },
            "PL_F": {
                        "var": 2866.049669,
                        "price": 1638.1,
                        "sector": "Commodities",
                        "description": "Platinum January",
                        "asset_class": "futures",
                        "atr_d1": 44.171429,
                        "atr_w1": 108.457143,
                        "atr_mn1": 144.021429,
                        "outliers": [],
                        "ev_data": {}
            },
            "RB_X": {
                        "var": 1746.182953,
                        "price": 1.9327,
                        "sector": "Commodities",
                        "description": "RBOB Gasoline November",
                        "asset_class": "futures",
                        "atr_d1": 0.040614,
                        "atr_w1": 0.0972,
                        "atr_mn1": 0.200593,
                        "outliers": [],
                        "ev_data": {}
            },
            "RTY_Z": {
                        "var": 1841.807447,
                        "price": 2450.2,
                        "sector": "Indexes",
                        "description": "E-Mini Rusell 2000 Index December",
                        "asset_class": "futures",
                        "atr_d1": 38.964286,
                        "atr_w1": 93.835714,
                        "atr_mn1": 231.657143,
                        "outliers": [],
                        "ev_data": {}
            },
            "SI_Z": {
                        "var": 5562.635527,
                        "price": 47.025,
                        "sector": "Commodities",
                        "description": "Silver December",
                        "asset_class": "futures",
                        "atr_d1": 1.064643,
                        "atr_w1": 2.086786,
                        "atr_mn1": 4.190357,
                        "outliers": [],
                        "ev_data": {}
            },
            "YM_Z": {
                        "var": 2023.235635,
                        "price": 46613.0,
                        "sector": "Indexes",
                        "description": "E-Mini DJIA December",
                        "asset_class": "futures",
                        "atr_d1": 416.571429,
                        "atr_w1": 1069.642857,
                        "atr_mn1": 2733.428571,
                        "outliers": [],
                        "ev_data": {}
            },
            "ZC_Z": {
                        "var": 336.166928,
                        "price": 421.25,
                        "sector": "Commodities",
                        "description": "Corn December",
                        "asset_class": "futures",
                        "atr_d1": 5.785714,
                        "atr_w1": 16.982143,
                        "atr_mn1": 40.017857,
                        "outliers": [],
                        "ev_data": {}
            },
            "ZL_Z": {
                        "var": 604.826546,
                        "price": 49.59,
                        "sector": "Commodities",
                        "description": "Soybean Oil December",
                        "asset_class": "futures",
                        "atr_d1": 1.109286,
                        "atr_w1": 2.519286,
                        "atr_mn1": 5.132143,
                        "outliers": [],
                        "ev_data": {}
            },
            "ZM_Z": {
                        "var": 353.98591,
                        "price": 275.0,
                        "sector": "Commodities",
                        "description": "Soybean Meal December",
                        "asset_class": "futures",
                        "atr_d1": 3.864286,
                        "atr_w1": 10.085714,
                        "atr_mn1": 30.257143,
                        "outliers": [],
                        "ev_data": {}
            },
            "ZN_Z": {
                        "var": 440.703731,
                        "price": 112.5,
                        "sector": "Financial",
                        "description": "10Y US Treasury Note December",
                        "asset_class": "futures",
                        "atr_d1": 0.429688,
                        "atr_w1": 1.007813,
                        "atr_mn1": 2.909598,
                        "outliers": [],
                        "ev_data": {}
            },
            "ZS_X": {
                        "var": 605.481499,
                        "price": 1009.25,
                        "sector": "Commodities",
                        "description": "Soybeans November",
                        "asset_class": "futures",
                        "atr_d1": 12.428571,
                        "atr_w1": 35.553571,
                        "atr_mn1": 77.125,
                        "outliers": [],
                        "ev_data": {}
            },
            "FDAX_Z": {
                        "var": 7553.07891,
                        "price": 23895.0,
                        "sector": "Indexes",
                        "description": "DAX Index December",
                        "asset_class": "futures",
                        "atr_d1": 264.785714,
                        "atr_w1": 656.357143,
                        "atr_mn1": 1523.857143,
                        "outliers": [],
                        "ev_data": {}
            },
            "FESX_Z": {
                        "var": 555.209192,
                        "price": 5523.0,
                        "sector": "Indexes",
                        "description": "Euro Stoxx 50 December",
                        "asset_class": "futures",
                        "atr_d1": 55.642857,
                        "atr_w1": 142.5,
                        "atr_mn1": 369.928571,
                        "outliers": [],
                        "ev_data": {}
            },
            "FGBL_Z": {
                        "var": 434.709103,
                        "price": 128.65,
                        "sector": "Indexes",
                        "description": "Bund December",
                        "asset_class": "futures",
                        "atr_d1": 0.425,
                        "atr_w1": 1.126429,
                        "atr_mn1": 3.345714,
                        "outliers": [],
                        "ev_data": {}
            }
};

// Make varData available globally
window.varData = varData;